In [1]:
# Odev 6 Alistirma 1
# Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.
# Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

import numpy as np

dizi1 = np.array([10, 20, 30, 40, 50], dtype='int')
print("Dizi:", dizi1)
print("Boyut:", dizi1.ndim)
print("Eleman Sayısı:", dizi1.size)


Dizi: [10 20 30 40 50]
Boyut: 1
Eleman Sayısı: 5


In [4]:
# Odev 6 Alistirma 2
# iki boyutlu ve üç boyutlu arrayi oluşturalım. 
# Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

import numpy as np

dizi2d = np.array([
    [1, 2, 6, 7],
    [4, 3, 9, 5]
])

dizi3d = np.array([
    [[7, 5, 14], [21, 8, 11]], 
    [[8, 6, 20], [14, 3, 9]]
])

print(f"2D Seri -> Boyut: {dizi2d.ndim}, Size: {dizi2d.size}, Shape (Satır,Sütun): {dizi2d.shape}")
print(f"3D Seri -> Boyut: {dizi3d.ndim}, Size: {dizi3d.size}, Shape (Katman,Satır,Sütun): {dizi3d.shape}")
print("-" * 30)

# Alistirma 3
# İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.
# İki boyutlu arraydaki 2 elemanına ulaşalım.
# İki boyutlu arraydaki 7 elemanına ulaşalım.
# Üç boyutlu arraydaki 9 elemanına ulaşalım.
# Üç boyutlu arraydaki 5 elemanına ulaşalım.

print("\nIndeksleme (Elemanlara Ulaşma)")

print("2B'deki 2 elemanı:", dizi2d[0, 1])
print("2B'deki 7 elemanı:", dizi2d[0, 3])

# Mantık: [Katman, Satır, Sütun]
print("3B'deki 9 elemanı:", dizi3d[1, 1, 2])
print("3B'deki 5 elemanı:", dizi3d[0, 0, 1])
print("-" * 30)

# Alistirma 4
# Arrayler üzerinde slicing işlemi uygulayalım.
# İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.
# İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.
# Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.
# Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

print("2D'deki 2,6 dilimi:", dizi2d[0, 1:3])
print("2D'deki 3,9,5 dilimi:", dizi2d[1, 1:])
print("3D'deki 21,8,11 dilimi:", dizi3d[0, 1, :])
print("3D'deki 6,20 dilimi:", dizi3d[1, 1, 1:])
print("-" * 30)

# Alistirma 5
# 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

sifirlar = np.zeros((5, 3), dtype='int')
birler = np.ones((5, 3), dtype='int')

print("Sıfırlar Dizisi:\n", sifirlar)
print("Birler Dizisi:\n", birler)

# Satır bazında birleştirme (Alt alta ekler - axis=0)
birlestir_satir = np.concatenate([sifirlar, birler], axis=0)
print("\nSatır Bazında Birleşim (Shape):", birlestir_satir.shape)

# Sütun bazında birleştirme (Yan yana ekler - axis=1)
birlestir_sutun = np.concatenate([sifirlar, birler], axis=1)
print("Sütun Bazında Birleşim (Shape):", birlestir_sutun.shape)

2D Seri -> Boyut: 2, Size: 8, Shape (Satır,Sütun): (2, 4)
3D Seri -> Boyut: 3, Size: 12, Shape (Katman,Satır,Sütun): (2, 2, 3)
------------------------------

Indeksleme (Elemanlara Ulaşma)
2B'deki 2 elemanı: 2
2B'deki 7 elemanı: 7
3B'deki 9 elemanı: 9
3B'deki 5 elemanı: 5
------------------------------
2D'deki 2,6 dilimi: [2 6]
2D'deki 3,9,5 dilimi: [3 9 5]
3D'deki 21,8,11 dilimi: [21  8 11]
3D'deki 6,20 dilimi: [3 9]
------------------------------
Sıfırlar Dizisi:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Birler Dizisi:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Satır Bazında Birleşim (Shape): (10, 3)
Sütun Bazında Birleşim (Shape): (5, 6)
